services:
  - type: web
    name: aura-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aura-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: OWM_API_KEY
        sync: false

databases:
  - name: aura-db
    plan: free